apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "hello from kubernetez"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "info,health,palTrackerFailure"